### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sravan-s** [cedricbonhomme/Stegano#11]
Hi,
I have been searching around for steganography modules in Python

When I tried your library, just as in the example,

```
secret = lsb.hide(imageFilePath, "Big secret")
secret.save("Lenna-secret.JPG")
print(lsb.reveal("Lenna-secret.JPG"))
```

I got a syntax error:
```
  File "__init__.py", line 2, in <module>
    ceaser = __import__('ceaser')
  File "/home/sravan/python/mini/ceaser.py", line 3, in <module>
    from stegano import lsb
  File "/usr/local/lib/python2.7/dist-packages/stegano/__init__.py", line 7, in <module>
    from . import lsbset
  File "/usr/local/lib/python2.7/dist-packages/stegano/lsbset/__init__.py", line 4, in <module>
    from .lsbset import *
  File "/usr/local/lib/python2.7/dist-packages/stegano/lsbset/lsbset.py", line 76
    r, g, b, *a = img_list[generated_number]
             ^
SyntaxError: invalid syntax
```
Could you please help with this?

**Comment by cedricbonhomme** [comment]
Hi,

Yes, this is because this syntax is not valid with Python 2. You should try with Python 3.
Until recently the module is no more compatible with Python2. In fact there isn't any big problem with Python 2. But I prefer to focus on Python 3 for the future of this project.
Do you have a problem with Python 3 with your setttings?

**Comment by sravan-s** [comment]
I'm actually not a python dev.  I think I should install this with pip3, right? Let me try and update

**Comment by sravan-s** [comment]
Hi,

With python3, syntax error is resolved. I tried the examples from your tests and it's working :+1:

**Comment by cedricbonhomme** [comment]
OK, happy that it is finally working !

**Comment by sravan-s** [comment]
Thanks for the amazing library.

😊 If I have any queries in the future, should I ask here?

**Comment by cedricbonhomme** [comment]
You are welcome!

Absolutely yes, this is the right place!
