### ISSUE TITLE
add an abstract

### ISSUE THREAD

**Issue by jabbalaci** [cedricbonhomme/Stegano#13]
Please add a short description to the beginning of your project. I had to go to the tutorial to find out what it is actually. The following description would be perfect:

"Steganography is the art and science of writing hidden messages in such a way that no one, apart from the sender and intended recipient, suspects the existence of the message, a form of security through obscurity. Consequently, functions provided by Stéganô only hide messages, without encryption. Steganography is often used with cryptography."

**Comment by cedricbonhomme** [comment]
Thanks, added !
