### ISSUE TITLE
Rename the commands to have a common "stegano-" prefix

### ISSUE THREAD

**Issue by ivandardi** [cedricbonhomme/Stegano#14]
This is a really nice program/lib! However, one of the commands is just `lsb`. It's nor a good name for an executable, because it's not unique enough and might conflict with something else. Besides, you can't autocomplete it easily.

My suggestion is that you add a "stegano-" prefix to the commands, so you can do "stegano-lsb" to run the least significant bit algorithm. That way it doesn't conflict and you can also autocomplete it by pressing tab.

Alternatively, you could just have a "stegano" command and have the mode be a mandatory paratemer, like "stegano --mode lsb".

**Comment by cedricbonhomme** [comment]
Thank you very much for your comment.

I agree with you. I am not really happy with that. I already thought about your suggestions but I wasn't able to decide which choice would be the best.
Anyway, I'll choose the first suggestion. It is easier for me. And I plan to add other modules of steganography in the future (audio files, etc.).
I think that the second alternative induces a more complex command line for the user. But not sure...

**Comment by cedricbonhomme** [comment]
Commands are now prefix with "stegano-". The new release with these changes is deployed on pypi.
