### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by sandeshnaroju** [cedricbonhomme/Stegano#17]
I am getting below Error while trying to Install Stegano.

    sandesh@sandesh-HP-Pavilion-Notebook:~/stegano$ sudo pip install Stegano
    Downloading/unpacking Stegano
    Downloading Stegano-0.8.1.tar.gz (225kB): 225kB downloaded
    Running setup.py (path:/tmp/pip_build_root/Stegano/setup.py) egg_info for package Stegano
    Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/lib/python2.7/dist-packages (from Stegano)
    Requirement already satisfied (use --upgrade to upgrade): piexif in /usr/local/lib/python2.7/dist-packages 
    (from Stegano)
    Requirement already satisfied (use --upgrade to upgrade): crayons in /usr/local/lib/python2.7/dist-
    packages (from Stegano)
    Installing collected packages: Stegano
    Running setup.py install for Stegano
    changing mode of build/scripts-2.7/stegano-lsb from 644 to 755
    changing mode of build/scripts-2.7/stegano-lsb-set from 644 to 755
    changing mode of build/scripts-2.7/stegano-red from 644 to 755
    changing mode of build/scripts-2.7/stegano-steganalysis-parity from 644 to 755
    changing mode of build/scripts-2.7/stegano-steganalysis-statistics from 644 to 755
      File "/usr/local/lib/python2.7/dist-packages/stegano/lsb/lsb.py", line 35
        def hide(input_image: Union[str, IO[bytes]],
                            ^
    SyntaxError: invalid syntax
    
      File "/usr/local/lib/python2.7/dist-packages/stegano/lsbset/lsbset.py", line 36
        def hide(input_image: Union[str, IO[bytes]],
                            ^
    SyntaxError: invalid syntax
    
      File "/usr/local/lib/python2.7/dist-packages/stegano/lsbset/generators.py", line 32
        def identity() -> Iterator[int]:
                       ^
    SyntaxError: invalid syntax
    
      File "/usr/local/lib/python2.7/dist-packages/stegano/tools.py", line 38
        def a2bits(chars: str) -> str:
                        ^
    SyntaxError: invalid syntax
    
      File "/usr/local/lib/python2.7/dist-packages/stegano/red/red.py", line 33
        def hide(input_image: Union[str, IO[bytes]], message: str):
                            ^
    SyntaxError: invalid syntax
    
    changing mode of /usr/local/bin/stegano-steganalysis-parity to 755
    changing mode of /usr/local/bin/stegano-steganalysis-statistics to 755
    changing mode of /usr/local/bin/stegano-lsb-set to 755
    changing mode of /usr/local/bin/stegano-lsb to 755
    changing mode of /usr/local/bin/stegano-red to 755
    Successfully installed Stegano
    Cleaning up...

**Comment by cedricbonhomme** [comment]
Hello,

Can you try with Python 3? Python 2 is no more supported.

**Comment by cedricbonhomme** [comment]
If you do not have Python 3, you can try with pew: https://github.com/cedricbonhomme/Stegano#contributions
