### ISSUE TITLE
ImportError: cannot import name 'lsb'

### ISSUE THREAD

**Issue by mohrt** [cedricbonhomme/Stegano#19]
I had a heck of a time with this error:

ImportError: cannot import name 'lsb'

It ended up that my python script was named stegano.py, and this confused how the import was working. Apparently it looks for stegano.py in the package, and instead it loads the stegano.py file in my home folder. I changed my script name to something else and it began working.

**Comment by cedricbonhomme** [comment]
This is a common behavior of Python. Modules in the working directory have a higher priority of loading.
Renaming your script was a good thing to do. You can also simply install Stegano in your project with pipenv and then just load it in your script.
