### ISSUE TITLE
lsbset.hide cause .png transparent area lost

### ISSUE THREAD

**Issue by gitbobo** [cedricbonhomme/Stegano#23]
Thanks for this tool! 
Sample png file is https://i.postimg.cc/66CB3w1W/ori.png  
When run `lsb.hide(ori.png,"hello world")`,everything is ok.Open saved png with adobe photoshop, transparent area keeps well.  
But `lsbset.hide(ori.png,"hello world",generators.eratosthenes())` will lost the transparent area.

**Comment by cedricbonhomme** [comment]
Hi,
thanks for the report! I will have a loot at it!

**Comment by cedricbonhomme** [comment]
Fixed, thank you !
