### ISSUE TITLE
The Ackermann functions are not actual generators

### ISSUE THREAD

**Issue by AdrienCos** [cedricbonhomme/Stegano#24]
As the title mentions, the two [Ackermann number generators](https://github.com/cedricbonhomme/Stegano/blob/47f70cc820eb73e91c04d4e788ef0425b391841c/stegano/lsbset/generators.py#L110) in the file `generators.py` are not actual generators, for two reasons:
- they to not have any `yield` instruction, causing them to be considered as simple functions by the interpreter
- they do not operate in a loop, i.e. they output a single integer and finish

I believe that they should be rewritten to act as generator. A possible solution could be to have the generator start at `A(1,0)` (or any other value), and each new iteration would be `A(i, 0)`, where `i` is an incremental counter. 

Furthermore, the two generators cannot currently be called from the `stegano-lsb-set` command line tool, as they expect two arguments `n` and `m` to be passed to them. These arguments are currently not grabbed by the parser.

Edit: Added body of the issue

**Comment by cedricbonhomme** [comment]
Indeed you are correct. But the actual behavior is intended. But I'll look if I can improve this. Also if by chance your updates are working you can make a PR.

**Comment by AdrienCos** [comment]
By actual behaviour, do you mean generating a unique number, instead of a series of numbers? Or the fact that it cannot be called from the command line?

**Comment by cedricbonhomme** [comment]
Not usable from the command line.
You can use it when using Stegano as a library. But this is not a good function, it grows way to fast for iterating over pixels. At least when m>2.
So I was wondering if the better choice would be to move it in another module. I do not want to write too complex code just to solve this. Unless if I found something clean (for the command line).

**Comment by AdrienCos** [comment]
Right, the rate of increase was another concern I have about it. I guess it can be useful to hide very little information in a very large image. 

For the command line interface, I have figured out how to cleanly call the function and pass it its arguments. However, it is not very helpful, as the function only returns one number. This means that if you need more than 3 bits to store your data, it throw a StopIteration exception at the second call. If you changed the function to generate a series of numbers, then it could work.

**Comment by cedricbonhomme** [comment]
I think that passing only 'm' from the command line would be enough. I encapsulated the function in a generator:
https://github.com/cedricbonhomme/Stegano/commit/5694e5c806f2fba148cd59d1d32740eff756f0d5#diff-66cf8190313cbed61a14d04dc9a763d6R58

**Comment by AdrienCos** [comment]
I have added the feature for both ackermann generators (and encapsulated the slow one). The changes are available in the PR #26.
