### ISSUE TITLE
Improve the steganalysis.statistics feature

### ISSUE THREAD

**Issue by AdrienCos** [cedricbonhomme/Stegano#29]
# Issue
As of now, `steganalysis.statistics` is not very usable, for a few reasons:
1.  The CLI utility to call it is broken. It asks for an output file, and tries to save the output of the `steganalyse` function to it, which is not possible (as it is a tuple)
2. The `steganalyse` function itself is not very self-explanatory, and does not provide any meaningful output. From what I understand, it outputs the most common values of the red values of the image. 

# Steps to reproduce:
1. `stegano-steganalysis-statistics -i tests/sample-files/Lenna.png` outputs
```
Traceback (most recent call last):
  File "/Users/adrien/.local/share/virtualenvs/Stegano-IZOkUS3P/bin/stegano-steganalysis-statistics", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/adrien/dev/Stegano/bin/stegano-steganalysis-statistics", line 45, in <module>
    output_image.save(arguments.output_image_file)
AttributeError: 'tuple' object has no attribute 'save'
```

2. Run the following code in Python:
```
from stegano import steganalysis
from PIL import Image

name = "./tests/sample-files/Lenna.png"
image = Image.open(name)
print(steganalysis.statistics.steganalyse(image))
```
It outputs:
``` 
([58, 56, 54, 57, 60, 59, 62, 61, 63, 65, 64, 66, 67, 254, 68, 69, 255, 70, 253, 71, 72, 74, 252, 73, 251, 250, 75, 249, 76, 77], [(224, 4327), (221, 4138), (223, 4057), (222, 3987), (225, 3713), (220, 3554), (209, 3516), (207, 3476), (208, 3424), (219, 3360)])
```

# Suggestions
1. Change the CLI utility to not take an output file anymore, and not try to save any output, simply run the analysis
2. Give more context to the user about the data that is being output. Maybe add some new optional parameters (like analyze also the blue and green layers, output in CSV form, etc.)

If needed, I can work on implementing all of this, I would mostly need more information about what the statistics function is supposed to do.

**Comment by AdrienCos** [comment]
Based on #28, would it be OK if I altered the function a lot, to make it more useful than now?

**Comment by cedricbonhomme** [comment]
Indeed `steganalysis.statistics` is a bit useless... It has been written years ago and to be honest even for me it's not easy to clearly understand what to do with the output. I remember that I saw this in an article.

On the other hand, `steganalysis.parity` is simple but useful.

So yes, feel free to propose something completely different. I am not against basically removing `steganalysis.statistics`.
