### ISSUE TITLE
After reading with lsb, the image is closed

### ISSUE THREAD

**Issue by Starmania** [cedricbonhomme/Stegano#51]
Hey,

I was building on top of your library when I came across some odd behavior. After reading an image, it would close.

Except that after reading the image's secret text, I still need to do some processing on it. Right now I'm doing some Monkey Patching, but it's not great... 

Would it be possible not to close the image? Or just add a parameter to tell you not to close it?

Thanks a lot!

**Comment by cedricbonhomme** [comment]
Hi,

Are you doing some stuff with the result of Stegano ? If yes, why not opening the file on your side? Or maybe you are doing various processing before the end of the generation of the image by Stegano ? If you could explain a bit more, that would help. Thanks !

**Comment by Starmania** [comment]
Hey,

Here is my code, where I'm giving to the décoder the image. https://github.com/Starmania/getscrambled/blob/e69be36e48b5430ee54477b8a9c0e1e8e36332d4/getscrambled/decode.py#L38

**Comment by cedricbonhomme** [comment]
OK, I see. Not fan, but I added a parameter, ``close_file``. As you can see here:
https://github.com/cedricbonhomme/Stegano/blob/master/stegano/lsb/lsb.py#L70

It's already published on Pypi.

**Comment by Starmania** [comment]
I can understand why you're not fan of it, but this is still better than monkey patch an object....

Thanks you!
